-- MySQL Script generated by MySQL Workbench
-- Qua 30 Ago 2017 10:16:45 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema processoseletivo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema processoseletivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `processoseletivo` DEFAULT CHARACTER SET utf8 ;
USE `processoseletivo` ;

-- -----------------------------------------------------
-- Table `processoseletivo`.`emissores_rg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`emissores_rg` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`estados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` CHAR(2) NOT NULL,
  `paises_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estados_paises1_idx` (`paises_id` ASC),
  CONSTRAINT `fk_estados_paises1`
    FOREIGN KEY (`paises_id`)
    REFERENCES `processoseletivo`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`cidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estados_id` INT NOT NULL,
  `naturalidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidades_estados1_idx` (`estados_id` ASC),
  CONSTRAINT `fk_cidades_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `processoseletivo`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `rg` VARCHAR(45) NOT NULL,
  `emissor_rg_id` INT NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `passaporte` VARCHAR(45) NULL,
  `nome_pai` VARCHAR(45) NOT NULL,
  `nome_mae` VARCHAR(45) NOT NULL,
  `naturalidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_emissor_rg_idx` (`emissor_rg_id` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_pessoas_cidades1_idx` (`naturalidade_id` ASC),
  CONSTRAINT `fk_pessoa_emissor_rg`
    FOREIGN KEY (`emissor_rg_id`)
    REFERENCES `processoseletivo`.`emissores_rg` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_cidades1`
    FOREIGN KEY (`naturalidade_id`)
    REFERENCES `processoseletivo`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipos_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipos_enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidades_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  `tipos_enderecos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_enderecos_cidades1_idx` (`cidades_id` ASC),
  INDEX `fk_enderecos_pessoas1_idx` (`pessoas_id` ASC),
  INDEX `fk_enderecos_tipos_enderecos1_idx` (`tipos_enderecos_id` ASC),
  CONSTRAINT `fk_enderecos_cidades1`
    FOREIGN KEY (`cidades_id`)
    REFERENCES `processoseletivo`.`cidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enderecos_tipos_enderecos1`
    FOREIGN KEY (`tipos_enderecos_id`)
    REFERENCES `processoseletivo`.`tipos_enderecos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipos_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipos_telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `tipos_telefones_id` INT NOT NULL,
  `pessoas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telefones_tipos_telefones1_idx` (`tipos_telefones_id` ASC),
  INDEX `fk_telefones_pessoas1_idx` (`pessoas_id` ASC),
  CONSTRAINT `fk_telefones_tipos_telefones1`
    FOREIGN KEY (`tipos_telefones_id`)
    REFERENCES `processoseletivo`.`tipos_telefones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefones_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`escolaridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`escolaridades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipos_escolaridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipos_escolaridades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoas_escolaridades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoas_escolaridades` (
  `pessoas_id` INT NOT NULL,
  `escolaridades_id` INT NOT NULL,
  `tipos_escolaridades_id` INT NOT NULL,
  PRIMARY KEY (`pessoas_id`, `escolaridades_id`, `tipos_escolaridades_id`),
  INDEX `fk_pessoas_has_escolaridades_escolaridades1_idx` (`escolaridades_id` ASC),
  INDEX `fk_pessoas_has_escolaridades_pessoas1_idx` (`pessoas_id` ASC),
  INDEX `fk_pessoas_escolaridades_tipos_escolaridades1_idx` (`tipos_escolaridades_id` ASC),
  CONSTRAINT `fk_pessoas_has_escolaridades_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_escolaridades_escolaridades1`
    FOREIGN KEY (`escolaridades_id`)
    REFERENCES `processoseletivo`.`escolaridades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_escolaridades_tipos_escolaridades1`
    FOREIGN KEY (`tipos_escolaridades_id`)
    REFERENCES `processoseletivo`.`tipos_escolaridades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`usuarios` (
  `pessoas_id` INT NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  INDEX `fk_usuarios_pessoas1_idx` (`pessoas_id` ASC),
  PRIMARY KEY (`pessoas_id`),
  CONSTRAINT `fk_usuarios_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`notificacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`usuarios_notificacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`usuarios_notificacoes` (
  `usuarios_pessoas_id` INT NOT NULL,
  `notificacoes_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_pessoas_id`, `notificacoes_id`),
  INDEX `fk_usuarios_has_notificacoes_notificacoes1_idx` (`notificacoes_id` ASC),
  INDEX `fk_usuarios_has_notificacoes_usuarios1_idx` (`usuarios_pessoas_id` ASC),
  CONSTRAINT `fk_usuarios_has_notificacoes_usuarios1`
    FOREIGN KEY (`usuarios_pessoas_id`)
    REFERENCES `processoseletivo`.`usuarios` (`pessoas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_notificacoes_notificacoes1`
    FOREIGN KEY (`notificacoes_id`)
    REFERENCES `processoseletivo`.`notificacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`necessidades_especiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`necessidades_especiais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`pessoas_necessidades_especiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`pessoas_necessidades_especiais` (
  `pessoas_id` INT NOT NULL,
  `necessidades_especiais_id` INT NOT NULL,
  `permanente` TINYINT(1) NOT NULL,
  `observacao` TEXT NULL,
  PRIMARY KEY (`pessoas_id`, `necessidades_especiais_id`),
  INDEX `fk_pessoas_has_necessidades_especiais_necessidades_especiai_idx` (`necessidades_especiais_id` ASC),
  INDEX `fk_pessoas_has_necessidades_especiais_pessoas1_idx` (`pessoas_id` ASC),
  CONSTRAINT `fk_pessoas_has_necessidades_especiais_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_necessidades_especiais_necessidades_especiais1`
    FOREIGN KEY (`necessidades_especiais_id`)
    REFERENCES `processoseletivo`.`necessidades_especiais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`tipos_processos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`tipos_processos` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`processos_seletivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`processos_seletivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `inicio` DATETIME NOT NULL,
  `fim` DATETIME NOT NULL,
  `tipos_processos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_processos_seletivos_tipos_processos1_idx` (`tipos_processos_id` ASC),
  CONSTRAINT `fk_processos_seletivos_tipos_processos1`
    FOREIGN KEY (`tipos_processos_id`)
    REFERENCES `processoseletivo`.`tipos_processos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`taxas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`taxas` (
  `processos_seletivos_id` INT NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `vencimento_boleto` DATE NOT NULL,
  INDEX `fk_taxas_processos_seletivos1_idx` (`processos_seletivos_id` ASC),
  PRIMARY KEY (`processos_seletivos_id`),
  CONSTRAINT `fk_taxas_processos_seletivos1`
    FOREIGN KEY (`processos_seletivos_id`)
    REFERENCES `processoseletivo`.`processos_seletivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`cursos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`inscricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`inscricao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoas_id` INT NOT NULL,
  `processos_seletivos_id` INT NOT NULL,
  `data_pagto_taxa` DATE NULL,
  `primeira_opcao_id` INT NOT NULL,
  `segunda_opcao_id` INT NULL,
  `data_inscricao` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoas_has_processos_seletivos_processos_seletivos1_idx` (`processos_seletivos_id` ASC),
  INDEX `fk_pessoas_has_processos_seletivos_pessoas1_idx` (`pessoas_id` ASC),
  INDEX `fk_inscricao_cursos1_idx` (`primeira_opcao_id` ASC),
  INDEX `fk_inscricao_cursos2_idx` (`segunda_opcao_id` ASC),
  CONSTRAINT `fk_pessoas_has_processos_seletivos_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_processos_seletivos_processos_seletivos1`
    FOREIGN KEY (`processos_seletivos_id`)
    REFERENCES `processoseletivo`.`processos_seletivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_cursos1`
    FOREIGN KEY (`primeira_opcao_id`)
    REFERENCES `processoseletivo`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricao_cursos2`
    FOREIGN KEY (`segunda_opcao_id`)
    REFERENCES `processoseletivo`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`isencoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`isencoes` (
  `inscricao_id` INT NOT NULL,
  `motivo` TEXT NOT NULL,
  `homologada` TINYINT(1) NULL,
  `pessoas_id` INT NOT NULL,
  INDEX `fk_isencoes_inscricao1_idx` (`inscricao_id` ASC),
  INDEX `fk_isencoes_pessoas1_idx` (`pessoas_id` ASC),
  CONSTRAINT `fk_isencoes_inscricao1`
    FOREIGN KEY (`inscricao_id`)
    REFERENCES `processoseletivo`.`inscricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_isencoes_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `processoseletivo`.`comissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `processoseletivo`.`comissao` (
  `pessoas_id` INT NOT NULL,
  `processos_seletivos_id` INT NOT NULL,
  PRIMARY KEY (`pessoas_id`, `processos_seletivos_id`),
  INDEX `fk_pessoas_has_processos_seletivos_processos_seletivos2_idx` (`processos_seletivos_id` ASC),
  INDEX `fk_pessoas_has_processos_seletivos_pessoas2_idx` (`pessoas_id` ASC),
  CONSTRAINT `fk_pessoas_has_processos_seletivos_pessoas2`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `processoseletivo`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_processos_seletivos_processos_seletivos2`
    FOREIGN KEY (`processos_seletivos_id`)
    REFERENCES `processoseletivo`.`processos_seletivos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `processoseletivo`.`tipos_enderecos`
-- -----------------------------------------------------
START TRANSACTION;
USE `processoseletivo`;
INSERT INTO `processoseletivo`.`tipos_enderecos` (`id`, `descricao`) VALUES (1, 'comercial');
INSERT INTO `processoseletivo`.`tipos_enderecos` (`id`, `descricao`) VALUES (2, 'residencial');

COMMIT;


-- -----------------------------------------------------
-- Data for table `processoseletivo`.`tipos_telefones`
-- -----------------------------------------------------
START TRANSACTION;
USE `processoseletivo`;
INSERT INTO `processoseletivo`.`tipos_telefones` (`id`, `descricao`) VALUES (1, 'comercial');
INSERT INTO `processoseletivo`.`tipos_telefones` (`id`, `descricao`) VALUES (2, 'residencial');

COMMIT;


-- -----------------------------------------------------
-- Data for table `processoseletivo`.`escolaridades`
-- -----------------------------------------------------
START TRANSACTION;
USE `processoseletivo`;
INSERT INTO `processoseletivo`.`escolaridades` (`id`, `descricao`) VALUES (1, 'ensino fundamental');
INSERT INTO `processoseletivo`.`escolaridades` (`id`, `descricao`) VALUES (2, 'ensino médio');

COMMIT;


-- -----------------------------------------------------
-- Data for table `processoseletivo`.`tipos_escolaridades`
-- -----------------------------------------------------
START TRANSACTION;
USE `processoseletivo`;
INSERT INTO `processoseletivo`.`tipos_escolaridades` (`id`, `descricao`) VALUES (1, 'escola publica');
INSERT INTO `processoseletivo`.`tipos_escolaridades` (`id`, `descricao`) VALUES (2, 'escola privada');
INSERT INTO `processoseletivo`.`tipos_escolaridades` (`id`, `descricao`) VALUES (3, 'privada com bolsa');

COMMIT;


-- -----------------------------------------------------
-- Data for table `processoseletivo`.`necessidades_especiais`
-- -----------------------------------------------------
START TRANSACTION;
USE `processoseletivo`;
INSERT INTO `processoseletivo`.`necessidades_especiais` (`id`, `descricao`) VALUES (1, 'VISUAL');
INSERT INTO `processoseletivo`.`necessidades_especiais` (`id`, `descricao`) VALUES (2, 'AUDITIVADA');
INSERT INTO `processoseletivo`.`necessidades_especiais` (`id`, `descricao`) VALUES (3, 'FISICA');
INSERT INTO `processoseletivo`.`necessidades_especiais` (`id`, `descricao`) VALUES (4, 'MENTAL');

COMMIT;

